//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18408
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.18408。
// 
#pragma warning disable 1591

namespace PLI.AD_AUTH {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AD_AUTHSoap", Namespace="http://tempuri.org/")]
    public partial class AD_AUTH : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AD_Authenticate_With_XMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback AD_Authenticate_With_JSONOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AD_AUTH() {
            this.Url = global::PLI.Properties.Settings.Default.PLI_AD_AUTH_AD_AUTH;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AD_Authenticate_With_XMLCompletedEventHandler AD_Authenticate_With_XMLCompleted;
        
        /// <remarks/>
        public event AD_Authenticate_With_JSONCompletedEventHandler AD_Authenticate_With_JSONCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AD_Authenticate_With_XML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AD_Authenticate_With_XML(string _serverName, string _domain, string _username, string _pwd) {
            object[] results = this.Invoke("AD_Authenticate_With_XML", new object[] {
                        _serverName,
                        _domain,
                        _username,
                        _pwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AD_Authenticate_With_XMLAsync(string _serverName, string _domain, string _username, string _pwd) {
            this.AD_Authenticate_With_XMLAsync(_serverName, _domain, _username, _pwd, null);
        }
        
        /// <remarks/>
        public void AD_Authenticate_With_XMLAsync(string _serverName, string _domain, string _username, string _pwd, object userState) {
            if ((this.AD_Authenticate_With_XMLOperationCompleted == null)) {
                this.AD_Authenticate_With_XMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAD_Authenticate_With_XMLOperationCompleted);
            }
            this.InvokeAsync("AD_Authenticate_With_XML", new object[] {
                        _serverName,
                        _domain,
                        _username,
                        _pwd}, this.AD_Authenticate_With_XMLOperationCompleted, userState);
        }
        
        private void OnAD_Authenticate_With_XMLOperationCompleted(object arg) {
            if ((this.AD_Authenticate_With_XMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AD_Authenticate_With_XMLCompleted(this, new AD_Authenticate_With_XMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AD_Authenticate_With_JSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AD_Authenticate_With_JSON(string _serverName, string _domain, string _username, string _pwd) {
            object[] results = this.Invoke("AD_Authenticate_With_JSON", new object[] {
                        _serverName,
                        _domain,
                        _username,
                        _pwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AD_Authenticate_With_JSONAsync(string _serverName, string _domain, string _username, string _pwd) {
            this.AD_Authenticate_With_JSONAsync(_serverName, _domain, _username, _pwd, null);
        }
        
        /// <remarks/>
        public void AD_Authenticate_With_JSONAsync(string _serverName, string _domain, string _username, string _pwd, object userState) {
            if ((this.AD_Authenticate_With_JSONOperationCompleted == null)) {
                this.AD_Authenticate_With_JSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAD_Authenticate_With_JSONOperationCompleted);
            }
            this.InvokeAsync("AD_Authenticate_With_JSON", new object[] {
                        _serverName,
                        _domain,
                        _username,
                        _pwd}, this.AD_Authenticate_With_JSONOperationCompleted, userState);
        }
        
        private void OnAD_Authenticate_With_JSONOperationCompleted(object arg) {
            if ((this.AD_Authenticate_With_JSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AD_Authenticate_With_JSONCompleted(this, new AD_Authenticate_With_JSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AD_Authenticate_With_XMLCompletedEventHandler(object sender, AD_Authenticate_With_XMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AD_Authenticate_With_XMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AD_Authenticate_With_XMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AD_Authenticate_With_JSONCompletedEventHandler(object sender, AD_Authenticate_With_JSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AD_Authenticate_With_JSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AD_Authenticate_With_JSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591